name: gobase64

on:
  push:
    branches: ["main", "feat/github-action"]
    tags: ["v*"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: scripts
        run: |
          node -v
          npm -v

      - name: build and push
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "triggered by tag pushing"
          echo $VERSION
          echo ${{  github.ref_name }}
          echo ${GITHUB_REF#refs/tags/}

      - name: test
        run: |
          uname -a
          echo $VERSION
          env
